### ISSUE TITLE
EddystoneUID with only 18 datalength

### ISSUE THREAD

**Issue by EwaRvr** [futomi/node-beacon-scanner#3]
I am using Kontakt.IO beacons in Eddystone UID setting, however, those beacons only include 18 characters of data. 
As nowhere in the code you use the last 2 digits, in file lib/parser-eddystone.js would you be opposed to changing line 82 to `if(data.length !== 20 && data.length !== 18) {`?

Also, I would love to see the ability to pass in a parameter into the scanner to enable the return of any non-supported beacon formats from the parser (similar to https://github.com/cagdasakar/mechanic-ble-scanner/blob/master/lib/parser.js, just turned on by a parameter for backwards compatibility.
It would have helped me tremendously with discovering the above issue, as I would have been able to see the tags come through unparsed, rather than just being absent.

I can create a pull request for both if you like?

**Comment by futomi** [comment]
Thank you so much for your feedback. As you reported, I found that the size of the Eddystone-UID packet from Kontakt device is 18 bytes. I updated the node-beacon-scanner. Try the latest version.

**Comment by EwaRvr** [comment]
Great! thank you!
