### ISSUE TITLE
iBeacon packet does not contain the estimote proximity value?

### ISSUE THREAD

**Issue by ayeshx** [futomi/node-beacon-scanner#4]
Does the iBeacon advertisement object received by us contain the proximity value? 
Like Immediate, Far, Near ?

**Comment by futomi** [comment]
Sorry my reply is late. 

> Does the iBeacon advertisement object received by us contain the proximity value?

No. The information of the proximity is not set in iBeacon packets. It's calculated by iOS. Unfortunately, I don't know how to calculate the proximity. I think the proximity is calculated using RSSI. But I'm not sure.

**Comment by rafacompu** [comment]
Yes, the proximity is calculated with the RSSI. The signal is rather choppy so you will have to deal with the filtering as well.
