### ISSUE TITLE
Scan beacon using web browser, startScan() throw "Uncaught (in promise) TypeError"

### ISSUE THREAD

**Issue by 1isten** [futomi/node-beacon-scanner#5]
Hi futomi! I'm trying to use this tool in my web app (I'm using Vue.js, my platform environment is macOS 10.13.6, latest Google Chrome and node version is v8.12.0). Below is the situation:

I bind an on-click event to a button like below: 

`<button @click="scan()">Scan</button>`

and my js code in the same page is like below:

```
<script>
    const BeaconScanner = require('node-beacon-scanner');
    const scanner = new BeaconScanner();

    export default {
        methods: {
            scan() {
                // Set an Event handler for becons
                scanner.onadvertisement = (ad) => {
                    console.log(JSON.stringify(ad, null, '  '));
                };

                // Start scanning
                scanner.startScan().then(() => {
                    console.log('Started to scan.')  ;
                }).catch((error) => {
                    console.error(error);
                });
            }
        }
    }
</script>
```

But when I click the button, an error appears in Chrome's console:

```
Uncaught (in promise) TypeError: Failed to execute 'requestDevice' on 'Bluetooth': 'filters' member must be non-empty to find any devices.
    at NobleBindings.startScanning (app.js:53290)
    at Noble.scan (app.js:51724)
    at Noble.startScanning (app.js:51736)
    at Promise (app.js:50833)
    at new Promise (<anonymous>)
    at BeaconScanner._prepareScan (app.js:50832)
    at _init.then (app.js:50821)
NobleBindings.startScanning @ app.js:53290
scan @ app.js:51724
Noble.startScanning @ app.js:51736
Promise @ app.js:50833
BeaconScanner._prepareScan @ app.js:50832
_init.then @ app.js:50821
Promise.catch (async)
NobleBindings.startScanning @ app.js:53316
scan @ app.js:51724
Noble.startScanning @ app.js:51736
Promise @ app.js:50833
BeaconScanner._prepareScan @ app.js:50832
_init.then @ app.js:50821
Promise.then (async)
Promise @ app.js:50820
BeaconScanner.startScan @ app.js:50819
scan @ app.js:50754
click @ app.js:53959
invoker @ app.js:41284
fn._withTask.fn._withTask @ app.js:41083
```
I've Googled this error message but didn't find useful solution. Some information I found is about the Web-Bluetooth, I tried to enable chrome://flags/#enable-experimental-web-platform-features](url) flag and restart Google Chrome, still the same issue.

Is that mean this tool does not support web browser? Wish I have your suggestions. Thank you.

**Comment by hem-bhagat-tark** [comment]
Did you find the solution to this @1isten ? I am also wondering if this works with web browsers.

**Comment by 1isten** [comment]
@hem-bhagat-tark No, I've given up.

**Comment by hem-bhagat-tark** [comment]
Okay, @1isten . Do you have any other references related to beacons that I can refer to? I am basically exploring receiving beacon signals and I would like to know if it's possible to achieve that in a Web App.

**Comment by 1isten** [comment]
@hem-bhagat-tark No, I've stopped playing around with beacon thing since then...

**Comment by hem-bhagat-tark** [comment]
Okay. No problem.

**Comment by futomi** [comment]
@hem-bhagat-tark, this node module never work woth web browsers. It works only with node.js.
